version: '3.3'
services:
  mysql:
    build: ./docker/mysql
    ports: ["${MYSQL_HOST_PORT:?}:${MYSQL_CONTAINER_PORT:?}"]
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:?}
      MYSQL_DATABASE: ${DB_NAME:?}
      MYSQL_TEST_DATABASE: ${DB_TEST_NAME:?}
      MYSQL_USER: ${DB_USER:?}
      MYSQL_PASSWORD: ${DB_PASS:?}
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
  nginx:
    build: ./docker/nginx
    ports: ["${NGINX_HOST_PORT:?}:${NGINX_CONTAINER_PORT:?}"]
    environment:
      - NGINX_PORT=${NGINX_CONTAINER_PORT:?}
      - NGINX_HOST=${NGINX_HOST:?}
    volumes:
      - ./src:${APP_PATH:?}
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/nginx/command.sh:/etc/nginx/command.sh
      - ./docker/nginx/mime.types:/etc/nginx/mime.types
    depends_on: [php, node]
    command: /bin/bash -c /etc/nginx/command.sh

  php:
    build:
      context: ./docker/php
      args:
        - APP_PATH=${APP_PATH:?}
        - APP_USER=${USER:?}

    stdin_open: true
    volumes: 
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./src:${APP_PATH:?}
    depends_on: [mysql]

  node:
    build: 
      context: ./docker/node
      args:
        - APP_PATH=${APP_PATH:?}
    stdin_open: true
    ports: ["8000:8000"]
    volumes:
      - ./src:${APP_PATH:?}